# Site settings
title: Spatial Non-Spatial STAR
#email:
description: EuroVis 2015 State of the Art Report
 # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: uic-evl

permalink: /:categories/:year/:month/:day/:title/

url: http://localhost
baseurl: ""

# Build settings
markdown: kramdown

lsi: false
highlighter: rouge
safe: true
incremental: false
gist:
    noscript: false

gems:
  - jekyll-sgitemap